package cn.t1tan.rules

import java.util.Map;
import cn.t1tan.auth.comm.AuthMessage
import cn.t1tan.auth.comm.AuthContext
import cn.t1tan.auth.enums.AuthReason
import cn.t1tan.auth.enums.AuthReason

global org.slf4j.Logger log

rule "[Message_001] 卡号是否上送"
	when
		context : AuthContext( checkPointList contains "Message_001" )
		AuthMessage (!exist("b002"))
	then
	    log.info("命中[Message_001],卡号未上送");
		context.getAuthReasonMap().put(AuthReason.R005, "Message_001");
end

rule "[Message_002] 金额是否上送"
	when
		context : AuthContext( checkPointList contains "Message_002" )
		AuthMessage (!exist("b004"))
	then
	    log.info("命中[Message_002],金额未上送");
		context.getAuthReasonMap().put(AuthReason.R005, "Message_002");
end